# SPDX-License-Identifier: MPL-2.0
"""Record provenance in a graph with the PROV-O terms and the secoro prov extension."""

from collections.abc import Iterable, Mapping
from datetime import datetime
from pathlib import Path

from rdflib import RDF, Graph, Literal, URIRef
from rdflib.namespace import DCTERMS, PROV, SDO

from rdf_utils.models.vocab import (
    URI_PROV_EXT_TYPE_EXECUTION,
    URI_PROV_EXT_TYPE_GENERALIZATION,
    URI_PROV_EXT_TYPE_TRANSFORMATION,
)


def _location_iri(location: str | URIRef) -> URIRef:
    if isinstance(location, URIRef) or "://" in location:
        return URIRef(location)
    return URIRef(Path(location).resolve().as_uri())


def _add_entity(graph: Graph, entity_id: URIRef, fmt: str | None = None) -> None:
    graph.add((entity_id, RDF.type, PROV.Entity))
    if fmt is not None:
        graph.add((entity_id, DCTERMS.format, Literal(fmt)))


def _add_activity(
    graph: Graph,
    activity_id: URIRef,
    subtype: URIRef,
    used: Iterable[URIRef],
    agent_id: URIRef,
    started: datetime,
    ended: datetime,
) -> None:
    graph.add((activity_id, RDF.type, PROV.Activity))
    graph.add((activity_id, RDF.type, subtype))
    for entity_id in used:
        graph.add((activity_id, PROV.used, entity_id))
    graph.add((activity_id, PROV.wasAssociatedWith, agent_id))
    graph.add((activity_id, PROV.startedAtTime, Literal(started)))
    graph.add((activity_id, PROV.endedAtTime, Literal(ended)))


def load_pkg_prov(
    graph: Graph,
    pkg_id: URIRef,
    name: str,
    version: str | None = None,
    commit: str | None = None,
    repository: str | None = None,
) -> URIRef:
    """Add a software package as a `prov:SoftwareAgent` described with schema.org terms."""
    graph.add((pkg_id, RDF.type, PROV.SoftwareAgent))
    graph.add((pkg_id, RDF.type, PROV.Agent))
    graph.add((pkg_id, SDO.name, Literal(name)))
    if version is not None:
        graph.add((pkg_id, SDO.softwareVersion, Literal(version)))
    if commit is not None:
        graph.add((pkg_id, SDO.identifier, Literal(commit)))
    if repository is not None:
        graph.add((pkg_id, SDO.codeRepository, URIRef(repository)))
    return pkg_id


def load_transformation_prov(
    graph: Graph,
    activity_id: URIRef,
    sources: Mapping[URIRef, str | None],
    targets: Mapping[URIRef, str | None],
    pkg_id: URIRef,
    started: datetime,
    ended: datetime,
) -> URIRef:
    """Add a `prov-ext:Transformation` by `pkg_id` of source entities into target entities.

    `sources` and `targets` map each entity to its media type, or None for no format.
    """
    for entity_id, fmt in sources.items():
        _add_entity(graph, entity_id, fmt)
    for entity_id, fmt in targets.items():
        _add_entity(graph, entity_id, fmt)
        graph.add((entity_id, PROV.wasGeneratedBy, activity_id))
    _add_activity(
        graph, activity_id, URI_PROV_EXT_TYPE_TRANSFORMATION, sources, pkg_id, started, ended
    )
    return activity_id


def load_sampling_prov(
    graph: Graph,
    activity_id: URIRef,
    used: Iterable[URIRef],
    generated: Iterable[URIRef],
    quantity_id: URIRef,
    agent_id: URIRef,
    started: datetime,
    ended: datetime,
) -> URIRef:
    """Add a `prov-ext:Generalization` that sampled `quantity_id` into the generated entities."""
    used = [*used, quantity_id]
    for entity_id in used:
        _add_entity(graph, entity_id)
    for entity_id in generated:
        _add_entity(graph, entity_id)
        graph.add((entity_id, PROV.wasGeneratedBy, activity_id))
    _add_activity(
        graph, activity_id, URI_PROV_EXT_TYPE_GENERALIZATION, used, agent_id, started, ended
    )
    return activity_id


def load_run_prov(
    graph: Graph,
    run_id: URIRef,
    used: Iterable[URIRef],
    agent_id: URIRef,
    started: datetime,
    ended: datetime,
) -> URIRef:
    """Add a `prov-ext:Execution` of the used entities by `agent_id`."""
    used = list(used)
    for entity_id in used:
        _add_entity(graph, entity_id)
    _add_activity(graph, run_id, URI_PROV_EXT_TYPE_EXECUTION, used, agent_id, started, ended)
    return run_id


def load_log_prov(
    graph: Graph,
    log_id: URIRef,
    run_id: URIRef,
    location: str | URIRef,
    generated_at: datetime,
    types: Iterable[URIRef] = (),
    fmt: str | None = None,
) -> URIRef:
    """Add a log file as a `prov:Entity` generated by `run_id`, located at a file IRI."""
    _add_entity(graph, log_id, fmt)
    for type_id in types:
        graph.add((log_id, RDF.type, type_id))
    graph.add((log_id, PROV.wasGeneratedBy, run_id))
    graph.add((log_id, PROV.atLocation, _location_iri(location)))
    graph.add((log_id, PROV.generatedAtTime, Literal(generated_at)))
    return log_id
